# Renders the launcher's settings into one REGEDIT4 file. The launcher imports
# it into the prefix whenever its store path changes, so every value that a
# setting can turn OFF is written explicitly (`=-` deletes it) — switching a
# setting back really reverts the prefix instead of leaving the old value.
{
  lib,
  theme,
  renderer,
  dpi,
  graphicsDriver,
  browser,
  extraRegistry,
}:
let
  dword = n: "dword:${lib.fixedWidthString 8 "0" (lib.toLower (lib.toHexString n))}";
  bool01 = b: dword (if b then 1 else 0);
  regString = s: ''"${lib.replaceStrings [ ''\'' ''"'' ] [ ''\\'' ''\"'' ] s}"'';

  dark = theme == "dark";

  themeSection = ''
    ; Logos follows the Windows app theme (uxtheme ShouldAppsUseDarkMode).
    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize]
    "AppsUseLightTheme"=${bool01 (!dark)}
    "SystemUsesLightTheme"=${bool01 (!dark)}

    ; Keep Wine's stock visual style and system colours. Logos paints resource
    ; panels with the system Window colour and picks text colours that assume
    ; the Windows defaults, so a dark system palette makes Bible text
    ; unreadable (dark on dark) in either Logos theme. These lines also undo
    ; the dark palette that logos-nix 0.1.0 wrote.
    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ThemeManager]
    "ThemeActive"="1"

    [-HKEY_CURRENT_USER\Control Panel\Colors]
  '';

  dxvkDlls = [
    "d3d8"
    "d3d9"
    "d3d10core"
    "d3d11"
    "dxgi"
  ];

  rendererSection =
    let
      d3dRenderer = if renderer == "dxvk" then "-" else regString renderer;
      override = if renderer == "dxvk" then regString "native,builtin" else "-";
    in
    ''
      ; renderer=${renderer}
      [HKEY_CURRENT_USER\Software\Wine\Direct3D]
      "renderer"=${d3dRenderer}

      [HKEY_CURRENT_USER\Software\Wine\DllOverrides]
      ${lib.concatMapStringsSep "\n" (d: ''"${d}"=${override}'') dxvkDlls}
    '';
in
''
  REGEDIT4

  ; Generated by logos-nix. Re-imported whenever the Nix configuration changes;
  ; edits made by hand in regedit/winecfg to these values will be overwritten.

  ; --- Settings from the community installer (FaithLife-Community/OuDedetai) ---
  [HKEY_CURRENT_USER\Software\Wine\DllOverrides]
  "winemenubuilder.exe"=""

  ; RGB subpixel font smoothing (winetricks fontsmooth=rgb)
  [HKEY_CURRENT_USER\Control Panel\Desktop]
  "FontSmoothing"="2"
  "FontSmoothingGamma"=${dword 1400}
  "FontSmoothingOrientation"=${dword 1}
  "FontSmoothingType"=${dword 2}
  "LogPixels"=${if dpi == null then "-" else dword dpi}

  ; Arial, copied into C:\windows\Fonts by the launcher. Logos crashes in
  ; "Copy Bible Verse" and on first-run "Continue" without it.
  [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
  "Arial (TrueType)"="arial.ttf"
  "Arial Bold (TrueType)"="arialbd.ttf"
  "Arial Italic (TrueType)"="ariali.ttf"
  "Arial Bold Italic (TrueType)"="arialbi.ttf"
  "Arial Black (TrueType)"="ariblk.ttf"

  ${rendererSection}
  [HKEY_CURRENT_USER\Software\Wine\Drivers]
  "Graphics"=${if graphicsDriver == null then "-" else regString graphicsDriver}

  [HKEY_CURRENT_USER\Software\Wine\WineBrowser]
  "Browsers"=${if browser == null then "-" else regString browser}

  ; --- Theme: ${theme} ---
  ${themeSection}
  ${extraRegistry}
''
