# Renders the launcher's settings into one REGEDIT4 file. The launcher imports
# it into the prefix whenever its store path changes, so every value that a
# setting can turn OFF is written explicitly (`=-` deletes it) — switching a
# setting back really reverts the prefix instead of leaving the old value.
{
  lib,
  theme,
  colors,
  renderer,
  dpi,
  graphicsDriver,
  browser,
  extraRegistry,
}:
let
  dword = n: "dword:${lib.fixedWidthString 8 "0" (lib.toLower (lib.toHexString n))}";
  bool01 = b: dword (if b then 1 else 0);
  regString = s: ''"${lib.replaceStrings [ ''\'' ''"'' ] [ ''\\'' ''\"'' ] s}"'';

  # "#rrggbb" or "rrggbb" -> "r g b" (what Control Panel\Colors stores).
  rgb =
    hex:
    let
      h = lib.removePrefix "#" hex;
      byte = i: toString (lib.fromHexString (builtins.substring i 2 h));
    in
    assert lib.assertMsg (
      builtins.match "[0-9a-fA-F]{6}" h != null
    ) "logos: colour '${hex}' is not of the form #rrggbb";
    "${byte 0} ${byte 2} ${byte 4}";

  # Windows system colours, driven by a small semantic palette. These colour
  # Wine-drawn UI only (msiexec, file pickers, message boxes, menus); Logos
  # draws its own windows and follows its in-app Application Theme.
  systemColors = with colors; {
    Background = background;
    AppWorkSpace = background;
    Window = background;
    WindowText = text;
    ButtonFace = surface;
    ButtonAlternateFace = surface;
    ButtonText = text;
    ButtonHilight = raised;
    ButtonLight = raised;
    ButtonShadow = border;
    ButtonDkShadow = shadow;
    Menu = surface;
    MenuBar = surface;
    MenuText = text;
    MenuHilight = accent;
    Scrollbar = surface;
    InfoWindow = raised;
    InfoText = text;
    GrayText = mutedText;
    Hilight = accent;
    HilightText = accentText;
    HotTrackingColor = accent;
    ActiveTitle = surface;
    GradientActiveTitle = surface;
    TitleText = text;
    InactiveTitle = background;
    GradientInactiveTitle = background;
    InactiveTitleText = mutedText;
    ActiveBorder = border;
    InactiveBorder = border;
    WindowFrame = border;
  };

  dark = theme == "dark";

  themeSection = ''
    ; Apps that ask Windows for the system theme (uxtheme ShouldAppsUseDarkMode)
    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize]
    "AppsUseLightTheme"=${bool01 (!dark)}
    "SystemUsesLightTheme"=${bool01 (!dark)}

  ''
  + (
    if dark then
      ''
        ; Wine's aero/light msstyles has no dark variant: turn it off so the
        ; system colours below are what Wine draws with.
        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ThemeManager]
        "ThemeActive"="0"

        [-HKEY_CURRENT_USER\Control Panel\Colors]

        [HKEY_CURRENT_USER\Control Panel\Colors]
        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (n: v: ''"${n}"="${rgb v}"'') systemColors)}
      ''
    else
      ''
        [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ThemeManager]
        "ThemeActive"="1"

        ; Wine falls back to its built-in defaults without this key.
        [-HKEY_CURRENT_USER\Control Panel\Colors]
      ''
  );

  dxvkDlls = [
    "d3d8"
    "d3d9"
    "d3d10core"
    "d3d11"
    "dxgi"
  ];

  rendererSection =
    let
      d3dRenderer = if renderer == "dxvk" then "-" else regString renderer;
      override = if renderer == "dxvk" then regString "native,builtin" else "-";
    in
    ''
      ; renderer=${renderer}
      [HKEY_CURRENT_USER\Software\Wine\Direct3D]
      "renderer"=${d3dRenderer}

      [HKEY_CURRENT_USER\Software\Wine\DllOverrides]
      ${lib.concatMapStringsSep "\n" (d: ''"${d}"=${override}'') dxvkDlls}
    '';
in
''
  REGEDIT4

  ; Generated by logos-nix. Re-imported whenever the Nix configuration changes;
  ; edits made by hand in regedit/winecfg to these values will be overwritten.

  ; --- Settings from the community installer (FaithLife-Community/OuDedetai) ---
  [HKEY_CURRENT_USER\Software\Wine\DllOverrides]
  "winemenubuilder.exe"=""

  ; RGB subpixel font smoothing (winetricks fontsmooth=rgb)
  [HKEY_CURRENT_USER\Control Panel\Desktop]
  "FontSmoothing"="2"
  "FontSmoothingGamma"=${dword 1400}
  "FontSmoothingOrientation"=${dword 1}
  "FontSmoothingType"=${dword 2}
  "LogPixels"=${if dpi == null then "-" else dword dpi}

  ; Arial, copied into C:\windows\Fonts by the launcher. Logos crashes in
  ; "Copy Bible Verse" and on first-run "Continue" without it.
  [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
  "Arial (TrueType)"="arial.ttf"
  "Arial Bold (TrueType)"="arialbd.ttf"
  "Arial Italic (TrueType)"="ariali.ttf"
  "Arial Bold Italic (TrueType)"="arialbi.ttf"
  "Arial Black (TrueType)"="ariblk.ttf"

  ${rendererSection}
  [HKEY_CURRENT_USER\Software\Wine\Drivers]
  "Graphics"=${if graphicsDriver == null then "-" else regString graphicsDriver}

  [HKEY_CURRENT_USER\Software\Wine\WineBrowser]
  "Browsers"=${if browser == null then "-" else regString browser}

  ; --- Theme: ${theme} ---
  ${themeSection}
  ${extraRegistry}
''
